version: '3'
services:
  db:
    image: mysql:5.7.23
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=abda
      - MYSQL_DATABASE=majoo
      - MYSQL_USER=i7nhjwryym62vg0w
      - MYSQL_PASSWORD=hg9r2mt0vswjuxnj
    ports:
      - "3306:3306"
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
