base:
  port: ':8080'


mysql:
  dsn: 'i7nhjwryym62vg0w:hg9r2mt0vswjuxnj@tcp(localhost:3306)/majoo?charset=utf8mb4&parseTime=True&loc=Local'

jwt:
  jwt_expiration: 2
  jwt_secret: "sadfasdfasdgasgfag"
